spring:
  application:
    name: msclientes
    instance_id: ${random.value}

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:uuksc-rereaussm-ero@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log